### ISSUE TITLE
Binding events to ganttRow & ganttRowLabel

### ISSUE THREAD

**Issue by rschenkel** [angular-gantt/angular-gantt#593]
I'm trying to bind to the click event for ganttRow and ganttRowLabel with the following code:

```javascript
api.directives.on.new($scope, function (directiveName, directiveScope, element) {
  console.log(directiveName);

  if (directiveName === 'ganttTask') {
    element.bind('click', function (event) {
      event.stopPropagation();
      console.log('ganttTask click performed');
    });
  } else if (directiveName === 'ganttRow') {
    element.bind('click', function (event) {
      event.stopPropagation();
      console.log('ganttRow click performed');
    });
  } else if (directiveName === 'ganttRowLabel') {
    element.bind('click', function () {
      event.stopPropagation();
      console.log('ganttRowLabel click performed');
    });
  }
});
```

However, ganttRow & ganttRowLabel are not sent to api.directives.on.new(scope, function (directiveName, directiveScope, element) on initial load and therefore are not bound.

Once a group is collapsed and and then expended again the directives are then loaded.

The following plunker is forked from your example and writes the directive name to the console:
http://plnkr.co/edit/V7FSsnG86nHZUc649qx8?p=preview

Thanks.

**Comment by rschenkel** [comment]
Hi, I was wondering if there was an update on this?  Thanks.

**Comment by gine** [comment]
I have exactly the same problem and i made the same step procedure to understand what happen until i find this post.

**Comment by gine** [comment]
Trying to find an option to start with all the row collapsed(to expand everything after the rendering), I have found(without reading the documentations) the option auto-expand:'none'.

Setting it to auto-expand:'false' the row event start to work again.

Then reading the documentation about this option i understand that It doesn't refer what i search but now the row event  works. Realy I don't know why.

**Comment by gine** [comment]
I have tryed to debug but after few hours i got only confusion.

The plugin DrawTask work everytime well with `directiveName=='ganttRow'` on `api.directives.on.new($scope, function (directiveName, directiveScope, element) `, so looking for some better explanation/fix,  i made a plugin similar to DrawTask to fix this problem. It's only a POC.

Here the plugin:
```
(function(){
    'use strict';
    angular.module('gantt.ganttrowfix', ['gantt']).directive('ganttRowFix', ['$document',  'ganttUtils', function(document, utils) {
        return {
            restrict: 'E',
            require: '^gantt',
            scope: {
                enabled: '=?',
            },
            link: function(scope, element, attrs, ganttCtrl) {
                var api = ganttCtrl.gantt.api;

                if (scope.enabled === undefined) {
                    scope.enabled = true;
                }

                api.directives.on.new(scope, function(directiveName, directiveScope, element) {
                    if (directiveName === 'ganttRow') {
                        var drawHandler = function(evt) {
                            var evtTarget = (evt.target ? evt.target : evt.srcElement);
                            var enabled = angular.isFunction(scope.enabled) ? scope.enabled(evt): scope.enabled;
                            if (enabled && evtTarget.className.indexOf('gantt-row') > -1) {
								//DO IT
                            }
                        };

                        element.on('dblclick', drawHandler);
                    }
                });

                api.directives.on.destroy(scope, function(directiveName, directiveScope, element) {
                    if (directiveName === 'ganttRow') {
                        element.off('dblclick', directiveScope.drawTaskHandler);
                    }
                });
            }
        };
    }]);
}());
```
Here how you must add the deps on gant module:

`angular.module("yourmodule",[	'gantt','gantt.tree', ..., 'gantt.ganttrowfix'])`

And here how enable it from your template:

```
<div name="yourgantt" 
       gantt  
       ...
       data="data" 
       api="options.api" >
			
     <gantt-tree 
          enabled="options.sideMode === 'Tree' || options.sideMode === 'TreeTable'" 
          header-content="options.treeHeaderContent" 
          keep-ancestor-on-filter-row="true"> 
     </gantt-tree>
     <gantt-row-fix enabled="true"></gantt-row-fix>
     ...
</div>
```
I hope that can help someone.

**Comment by gine** [comment]
@Toilal fixed? or what?

**Comment by Toilal** [comment]
Can you try to reproduce with current master ? I'm not sure but i have fixed issues related to click handling.

**Comment by gine** [comment]
I'm realy busy next week but i will try.

**Comment by waitingduck** [comment]
I am facing the same problem. 
When I do `console.log(directiveName);`, ganttRowBackground and ganttRow is not fired. 
@gine 's ganttRowFix solve my problem, but I wonder if it is possible fixed in angular-gantt.

Thanks!

**Comment by gine** [comment]
@waitingduck did you already tryed with the new version?

**Comment by waitingduck** [comment]
@gine I am currently using version 1.2.14
I just tried version 1.3.0 and the problem remains.

**Comment by Toilal** [comment]
And master ?

Le 8 févr. 2017 1:54 AM, "Wei-ting Cheng" <notifications@github.com> a
écrit :

**Comment by waitingduck** [comment]
@Toilal 
I just tried the master, and problem remains.

**Comment by gine** [comment]
@waitingduck thanks.

**Comment by Toilal** [comment]
I've forked the initial plunkr to use 1.3.0, and `ganttRow`, `ganttRowLabel` and `ganttRowBackground` directive events are properly raised...

http://plnkr.co/edit/IGjVLH9TjfCqwnUknRYx?p=preview

**Comment by waitingduck** [comment]
Maybe code is different issue than this one? 
I will find time to make a plunker of my issue. 
Thanks

**Comment by Toilal** [comment]
Ok, I close this one then. If you can reproduce your own issue in plunker, please create a new one because the initial plunkr is fixed when using latest release.

**Comment by gine** [comment]
what is different on my Gantt is that I have grouped row and opened by default. Whit this situation I need to collapse and then re-open the grouped row to have the a click event on row. if I start with group collapsed everything work well. @waitingduck do you have grouped row too?
